<?php
 $img=ImageCreateFromJPEG('C:\xampp\htdocs\20220811_121457.jpg');
 $width=ImageSx($img);
 $height=ImageSy($img);
 $x=$width/2;
 $y=$height/2;
 $scaledImg=ImageCreateTrueColor($x,$y);
 ImageCopyResampled($scaledImg,$img,0,0,0,0,$x,$y,$width,$height);
 ImagePNG($scaledImg);
?>